# Use the NVIDIA CUDA base image
FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu16.04

# Update packages and install necessary dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Download and install Anaconda in one step to reduce layer size
RUN wget --quiet --no-check-certificate https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh -O /tmp/anaconda.sh \
    && /bin/bash /tmp/anaconda.sh -b -p /opt/conda \
    && rm /tmp/anaconda.sh \
    && /opt/conda/bin/conda clean -afy

# Add Anaconda to PATH
ENV PATH="/opt/conda/bin:$PATH"

# Create the python39 conda environment
RUN /bin/bash -c "source /opt/conda/etc/profile.d/conda.sh && \
                 conda create -n python39 python=3.9 -y"

# Set environment variables
ENV PATH="/opt/conda/envs/python39/bin:$PATH"
ENV LD_LIBRARY_PATH="/opt/conda/envs/python39/lib"

# Setup work directory
RUN mkdir -p /work
WORKDIR /work
COPY . .

# Install Python dependencies in the python39 environment
RUN /bin/bash -c "source /opt/conda/etc/profile.d/conda.sh && \
                 conda activate python39 && \
                 pip install -e . && \
                 conda install cudatoolkit cudnn -y && \
                 pip install omegaconf"

# Set the default command to bash
CMD ["/bin/bash"]
